[BSP.Kernel.MM][1/1]{ mm: cont_pte_hugepage: add feature [V0.5] }
适用范围：{U/SM8550/OS14.0/kernel-5.15}
准入id：{OPPO-5348334}
分析：{
  Patch Set 1: cp from http://gerrit.scm.adc.com:8080/#/c/22768446/4
               conflict file: mm/page_alloc.c
  Patch Set 2: disable CONFIG_THP_ZSMALLOC
  Patch Set 3: compile fix - drivers/dma-buf/heaps/qcom_system_heap.c:65:10: fatal error: '../../../mm/chp_ext.h' file not found
    revert 3 files: kalama_GKI.config / qcom_dynamic_page_pool.c / qcom_system_heap.c
  Patch Set 4: chmod 644 include/linux/fs.h
  Patch Set 5: rebased
  Patch Set 6: fix crc - 同步kernel/common仓的修改
}
方案：{NA}
风险及影响[快/稳/省/功能/安全隐私]：{稳}
测试建议：{NA}
跨组依赖(topic name)：{NA}

Change-Id: If9274b7a533bb3a1bd3dfaed69533e5a7f96c8a5
Reviewed-on: http://gerrit.scm.adc.com:8080/23114326
almid-check: codebase <codebase@oppo.com>
code-check: cqc <oppo_codecheck@oppo.com>
Reviewed-by: 周华材-80209858 <zhouhuacai@oppo.com>
Reviewed-by: 崔晓刚-80205180 <cuixiaogang@oppo.com>
Reviewed-by: 欧阳润宇-80233393 <ouyangrunyu@oppo.com>
Owner-Check: pswbuild <pswbuild@oppo.com>
Reviewed-by: pswbuild <pswbuild@oppo.com>
Tested-by: pswbuild <pswbuild@oppo.com>