[BSP.Kernel.MM][1/1]{ mm_hybridswap: kernel-5.15: fix compile errors }
适用范围：{kernel-5.15}
准入id：{OPPO-4186602}
分析：{
error: ninja: 'device/qcom/kalama-kernel/vendor_dlkm/zsmalloc.ko', needed by 'out/target/product/kalama/vendor.img', missing and no known rule to make it
}
方案：{NA}
风险及影响[快/稳/省/功能/安全隐私]：{稳}
测试建议：{NA}
跨组依赖(topic name)：{NA}

Signed-off-by: liuhailong <liuhailong@oppo.com>
Change-Id: Ib9eea3f6588f748105def5896e7bc1bb6ae5c13b
Reviewed-on: http://gerrit.scm.adc.com:8080/16318397
almid-check: oppo codebase <codebase@oppo.com>
Reviewed-by: 龙 科培-isoftstone <v-longkepei@oppo.com>
code-check: oppo_codecheck <oppo_codecheck@oppo.com>
Reviewed-by: 周 华材 <zhouhuacai@oppo.com>
Owner-Check: pswbuild <pswbuild@oppo.com>
Tested-by: oppobuild <oppobuild@oppo.com>
Reviewed-by: 周 茂炜 <zhoumaowei@oppo.com>
Tested-by: 周 茂炜 <zhoumaowei@oppo.com>
Reviewed-by: pswbuild <pswbuild@oppo.com>
Tested-by: pswbuild <pswbuild@oppo.com>
(cherry picked from commit 78aa555dc241c4527c59814acb71603eb3c4cf7c)
Reviewed-on: http://gerrit.scm.adc.com:8080/16318352